apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: auth
    newName: ghcr.io/ggingggang/svc-auth
    newTag: 464b6a7398471e169930bef28f20d85d45639f0f
