apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: auth
    newName: ghcr.io/ggingggang/svc-auth
    newTag: 3e59b0dc8c03b16a8f435da3d70dfe4a4e5f064c
