apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: auth
    newName: ghcr.io/ggingggang/svc-auth
    newTag: 4c07d4b87133d6299b4ea1fe9c93ed8d2135deed
