apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: web
    newName: ghcr.io/ggingggang/svc-web
    newTag: 1f9f5794accc53f9e4be7962f7b1bc687d891364
