apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: web
    newName: ghcr.io/ggingggang/svc-web
    newTag: d77188d7596219bfe7dff598c2446277f51cbfa9
