apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: web
    newName: ghcr.io/ggingggang/svc-web
    newTag: bc027df20853bf7d0b1e6b8eb0c7939be0bc397a
