apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notify
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: notify
    newName: ghcr.io/ggingggang/svc-notify
    newTag: 10478abf4f2d23a9a037f96009d68a87d2fd5669

