apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notify
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: notify
    newName: ghcr.io/ggingggang/svc-notify
    newTag: bootstrap

