apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notify
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: notify
    newName: ghcr.io/ggingggang/svc-notify
    newTag: 6a58bd8e2becde621f30a8206b2c33bde4c4e237

