apiVersion: v1
kind: Service
metadata:
  name: notify
  namespace: notify
  labels:
    app.kubernetes.io/name: notify
spec:
  selector:
    app.kubernetes.io/name: notify
  ports:
    - name: http
      port: 8080
      targetPort: http

