apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notify
  namespace: notify
  labels:
    app.kubernetes.io/name: notify
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notify
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

