apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: core
    newName: ghcr.io/ggingggang/svc-core
    newTag: ba96a51b660d68d3c86d1f1acce68ac89c95836c
