apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: core
    newName: ghcr.io/ggingggang/svc-core
    newTag: 6c4afe37f66576aff245c0d2e98f1364c8e02399
