apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
images:
  - name: core
    newName: ghcr.io/ggingggang/svc-core
    newTag: d091b86ebf5d9f6921715faea13549dde1b7fb5a
