apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batch
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: batch
    newName: ghcr.io/ggingggang/svc-batch
    newTag: 9f871574a5315f5081e88210233a94832708a835
