apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batch
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: batch
    newName: ghcr.io/ggingggang/svc-batch
    newTag: 819681c4c7ea0cab6bb8f342ded609f7b604df68
